/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String night_bg = "assets/image/night_bg.png";
  static const String refresh_btn = "assets/image/refresh_btn.png";
  static const String home_bg = "assets/image/home_bg.png";
  static const String splash_bg = "assets/image/splash_bg.png";
  static const String ic_icon = "assets/image/ic_icon.png";
}
